// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240916134109_startPoint")]
    partial class startPoint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 75m,
                            Title = "Karagöz ve Hacivat"
                        },
                        new
                        {
                            Id = 2,
                            Price = 175m,
                            Title = "Mesnevi"
                        },
                        new
                        {
                            Id = 4,
                            Price = 200m,
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 5,
                            Price = 150m,
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 3,
                            Price = 375m,
                            Title = "Devlet"
                        },
                        new
                        {
                            Id = 6,
                            Price = 300m,
                            Title = "Savaş ve Barış"
                        },
                        new
                        {
                            Id = 7,
                            Price = 250m,
                            Title = "Karamazov Kardeşler"
                        },
                        new
                        {
                            Id = 8,
                            Price = 450m,
                            Title = "İlahi Komedya"
                        },
                        new
                        {
                            Id = 9,
                            Price = 125m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 10,
                            Price = 100m,
                            Title = "Hayvan Çiftliği"
                        },
                        new
                        {
                            Id = 11,
                            Price = 275m,
                            Title = "Don Kişot"
                        },
                        new
                        {
                            Id = 12,
                            Price = 175m,
                            Title = "Beyaz Zambaklar Ülkesi"
                        },
                        new
                        {
                            Id = 13,
                            Price = 225m,
                            Title = "Simyacı"
                        },
                        new
                        {
                            Id = 14,
                            Price = 375m,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 15,
                            Price = 500m,
                            Title = "Ulysses"
                        },
                        new
                        {
                            Id = 16,
                            Price = 95m,
                            Title = "Yeraltından Notlar"
                        },
                        new
                        {
                            Id = 17,
                            Price = 180m,
                            Title = "Madame Bovary"
                        },
                        new
                        {
                            Id = 18,
                            Price = 140m,
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 19,
                            Price = 125m,
                            Title = "Çalıkuşu"
                        },
                        new
                        {
                            Id = 20,
                            Price = 350m,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 21,
                            Price = 160m,
                            Title = "Kırmızı ve Siyah"
                        },
                        new
                        {
                            Id = 22,
                            Price = 300m,
                            Title = "Monte Cristo Kontu"
                        },
                        new
                        {
                            Id = 23,
                            Price = 180m,
                            Title = "Bülbülü Öldürmek"
                        },
                        new
                        {
                            Id = 24,
                            Price = 200m,
                            Title = "Germinal"
                        },
                        new
                        {
                            Id = 25,
                            Price = 80m,
                            Title = "Küçük Prens"
                        },
                        new
                        {
                            Id = 26,
                            Price = 275m,
                            Title = "Yüzyıllık Yalnızlık"
                        },
                        new
                        {
                            Id = 27,
                            Price = 90m,
                            Title = "Şeker Portakalı"
                        },
                        new
                        {
                            Id = 28,
                            Price = 125m,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 29,
                            Price = 230m,
                            Title = "Lolita"
                        },
                        new
                        {
                            Id = 30,
                            Price = 150m,
                            Title = "Babasız Evler"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
